name    'mjhas/postfix'
version '0.0.7'
source 'https://github.com/mjhas/postfix.git'
author 'mjhas'
license 'Apache License 2.0'
summary 'Postfix Module'
description 'This Postfix Module installs postfix and configures it using Augeas'
project_page 'https://github.com/mjhas/postfix'
